### ISSUE TITLE
split along multiple dimentions

### ISSUE THREAD

**Issue by jkatzs** [bearloga/gsc-utils#5] opened 2018-03-30 21:31 UTC
Ideally the data we capture is pivotable so that I can see, for instance, how Argentinian traffic on mobile v. desktop is doing over time and filter that by rich results or not.  I understand that that certain combinations are hard because the average changes, but I believe a weighted average can be post-processed using impression data.

**Comment by bearloga** [comment] 2018-04-20 20:15
Duplicate of #1, fixed in b5596f4cc2eeec983551632ccd7fbaa78e781aab

**Closed as completed by bearloga** 2018-04-20 20:15 UTC
